print("     **********     ")
print("   *            *   ")
print("  *    o     o   *  ")
print(" *        ^       * ")
print(" *      \___/     * ")
print("  *              *  ")
print("   *            *   ")
print("     **********     ")